# Generated by Django 5.1.4 on 2025-01-23 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('CHOOSE WALLET', 'CHOOSE WALLET'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('CASH APP', 'CASH APP'), ('PAYPAL', 'PAYPAL')], max_length=400)),
                ('payment_address', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('preferred_currency', models.CharField(blank=True, default='$', max_length=100, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile/images')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100, null=True)),
                ('user_password_in_text', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Annual Income')),
                ('citizenship_status', models.CharField(choices=[('US Citizen', 'US Citizen'), ('Non-US Citizen', 'Non-US Citizen')], default='Non-US Citizen', max_length=50)),
                ('capital', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Capital')),
                ('roi', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ROI')),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Bonus')),
                ('program_type', models.CharField(blank=True, choices=[('Short-Term', 'Short-Term'), ('Long-Term', 'Long-Term')], default='Short-Term', max_length=100, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, verbose_name='KYC Verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id_type', models.CharField(blank=True, choices=[('Driver Licence', 'Driver Licence'), ('National ID', 'National ID'), ('Passport', 'Passport')], max_length=200, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('front_id_image', models.FileField(blank=True, null=True, upload_to='identity/images')),
                ('back_id_image', models.FileField(blank=True, null=True, upload_to='identity/images')),
                ('utility_bill', models.FileField(blank=True, null=True, upload_to='identity/proof/utility')),
                ('ssn', models.CharField(blank=True, max_length=500, null=True)),
                ('citizenship_status', models.CharField(choices=[('US Citizen', 'US Citizen'), ('Non-US Citizen', 'Non-US Citizen')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('DEPOSIT REQUEST', 'DEPOSIT REQUEST'), ('WITHDRAWAL', 'WITHDRAWAL')], max_length=400)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmation_receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('payment_method', models.CharField(blank=True, choices=[('bank', 'bank'), ('crypto', 'crypto'), ('paypal', 'paypal'), ('cashapp', 'cashapp')], max_length=400)),
                ('is_tax', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('image', models.FileField(blank=True, null=True, upload_to='support/images/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT REQUEST', 'DEPOSIT REQUEST'), ('WITHDRAWAL', 'WITHDRAWAL')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
