# Generated by Django 5.1.4 on 2025-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('danger', 'danger'), ('success', 'success'), ('warning', 'warning')], default='', help_text='Select the Notification Type. ', max_length=100, verbose_name='Notification Type'),
            preserve_default=False,
        ),
    ]
