# Generated by Django 5.1.4 on 2025-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='utility_bill',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_submitted_kyc',
            field=models.BooleanField(default=False, help_text='This means that user has submitted verification for KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_verified_kyc',
            field=models.BooleanField(default=False, help_text='Tick if user has undergone KYC Verification and has been approved.', verbose_name='User is verified'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='marital_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='number_of_dependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kyc',
            name='proof_of_employment',
            field=models.FileField(blank=True, null=True, upload_to='identity/proof'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='proof_of_income',
            field=models.FileField(blank=True, null=True, upload_to='identity/proof'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='tax_identity_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='back_id_image',
            field=models.FileField(blank=True, null=True, upload_to='identity/proof'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='citizenship_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='front_id_image',
            field=models.FileField(blank=True, null=True, upload_to='identity/proof'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='government_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='government_id_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='ssn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
