# Generated by Django 5.1.4 on 2025-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Minimum Deposit')),
                ('maximum_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Maximum Deposit')),
                ('term_duration', models.CharField(default='10 Days', max_length=100)),
                ('payout_term', models.CharField(default='Term Basis', max_length=100)),
                ('capital_return', models.CharField(default='End of Term', max_length=100)),
                ('percentage_return', models.CharField(default='130%', max_length=100)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
            },
        ),
    ]
