# Generated by Django 5.1.4 on 2025-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_name',
            field=models.CharField(default='Universal Plan', max_length=100),
        ),
    ]
