# Generated by Django 5.1.4 on 2025-01-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_adminpaymentmethod_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
