# Generated by Django 5.1.4 on 2025-03-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(blank=True, max_length=400)),
                ('wallet_address', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name': 'Admin Wallet',
                'verbose_name_plural': 'Admin Wallets',
            },
        ),
    ]
