# Generated by Django 5.1.4 on 2025-03-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customuser_investment_customuser_program_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='program_bonus',
        ),
    ]
