# Generated by Django 5.1.4 on 2025-03-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='withdraw_source',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
