# Generated by Django 5.1.4 on 2025-03-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_payment_options_investment_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('Basic Plan', 'Basic Plan'), ('Standard Plan', 'Standard Plan'), ('Premium Plan', 'Premium Plan'), ('Elite Plan', 'Elite Plan')], max_length=400, null=True),
        ),
    ]
