# Generated by Django 5.1.4 on 2025-03-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_investment_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Successful', 'Successful')], default='Pending', max_length=400),
        ),
    ]
