# Generated by Django 5.1.4 on 2025-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_investment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='image_holding_id',
            field=models.FileField(blank=True, null=True, upload_to='identity/proof'),
        ),
    ]
